name: Publish Packages

on:
  push:
    branches:
      - main # 変更がプッシュされるブランチを指定

jobs:
  release:
    name: Release and Publish Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v4
        with:
          node-version: "14"
          cache: "pnpm"
      - run: pnpm install
      # - run: pnpm test

      - name: Create a new changeset (optional)
        run: pnpx changeset add

      - name: Commit changeset (optional)
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci(changeset): create changeset"

      - name: Version and Publish
        run: |
          pnpx changeset version
          pnpm publish -r --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
